services:
  minio:
    image: minio/minio:latest
    container_name: mdm_minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - ./dados:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    entrypoint: >
      /bin/sh -c "
        echo 'Aguardando MinIO aceitar conexões...';
        until mc alias set local http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin123}; do
          echo 'Ainda não pronto, tentando novamente em 3s...';
          sleep 3;
        done;
        echo 'Conexão bem-sucedida!';
        # Verificar se o bucket já existe, caso contrário, cria
        mc ls local/ppca-mdm || mc mb local/ppca-mdm;
        # Definir a política do bucket
        mc policy set public local/ppca-mdm;
        echo 'Bucket ppca-mdm criado/configurado.';
        exit 0;
      "
